language: R
sudo: false
cache: packages
after_success: if [ "$TRAVIS_OS_NAME" == "linux" ]; then Rscript -e 'covr::codecov(type
  = "all")'; fi
warnings_are_errors: true
before_deploy: if [ "$TRAVIS_OS_NAME" == "osx" ]; then rm -f *.tar.gz; fi
r_check_args: "--as-cran --install-args=--build"
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  api_key: 
    secure: YJE5harBiqjeYNs66lXd6aCWk22NXm0lVO3P6/+4AjvxYRmUwfUE3PzMjp+OjlBWHd+Yq0p0Qu5Ml8+850/Mh5uuDlRmsnwPPtfMb5hn4Ag2k437MYRWIJynPDK5WvozeA95md3pjfHZAsvE8CnC6w7QOou876scdYKthi6dImuH7NIjAEQ1lJypUiOGj+S/Q16LHVTdc58sUrGAIho/L28IqX9qdpVNEz5GtIe9rQpDKByRFKyJV43f65qpWWuaUn3sfF0A2pFk8/6+tVUJslARQBO7veKjnK+m2+WVRAaw4LKMyUcLKGWi4au5/qy6ftDEVa5CC/y2WfHEs44DzFoxEjPy3IdpbGxfuYDsaOiAwvISFAmR7hVPeCGGx9SG/DdVowYqJ+Pxu7WPLtVNMkNLs1dRI0cSBnto/YJg8Np+nirEqWNeKPTJRQxvd3lHK6R9EIOBAMTRYmxTLylQ9HGSzMcK2qAIn75+mQaRoZN8jtiIM9Q9AGE0wLMguqDxIJ9K8rLo3fYHF9xFRLbvBgOf1vkbA18AwrY0JNAWgNOpPeS+tRM4IlRkW0x+yAiwtG/pyLIX4zFmJ5qM+jwXBhu6inuGg24XFDND77HYtFe60GRc8FMo11BuJNMwPmpHM5x3GoLAi0UQ6iZ04jT6MGxf9VR0kzSAyLCCdRMmhgw=
  file: mscstts*.t*gz
  on:
    tags: true
    repo: muschellij2/mscstts
