language: R
sudo: false
cache: packages
after_success: if [ "$TRAVIS_OS_NAME" == "linux" ]; then Rscript -e 'covr::codecov(type
  = "all")'; fi
warnings_are_errors: true
before_deploy: if [ "$TRAVIS_OS_NAME" == "osx" ]; then rm -f *.tar.gz; fi
r_check_args: "--as-cran --install-args=--build"

deploy:
  provider: releases
  skip_cleanup: yes
  file_glob: yes
  api_key:
    secure: "y1MlW3GnSyBQMWPRHnAKm4X+EHla6n/9FqopAJtcPFNkyrMCVWdJqKEAq7JLyz2n/1B5S4dsEgnfAJyVuwtuwvtNto4wMg7U2E2cr7WNmhc4/fvFvlIYmxTBMrGgFuNqSpTUK5gfnCdNbGGC5N0IGoGiAgvDhbnQNPcGMdKSAcoJ8n+k3hhjgMUznD+0efnXmmMpt+6/qYvYZzp1DmkvZbeZw4K34UZdG85UHmmLm9ad7lY+ahrB9sMSr8PNzQ3uXb2a4oZNgviqJaHM0VaRfCsqkUtMC7JMC2gQygIY5j0+tXlKCBPqYL6cVNr/pHkecJ8Q60Fg/BcL18RYPAxmbDP+Hwcwq8HaBa7Osm7YAX4oeAw3dYLhllvj+54AR3XMfbXscBU/34xjIGmUh9Fbl3FKgO7V8h7TitHM1WrNQxLJ79QeM4PPPRyKVQc1roRH8p2bVKjqAjEGgTCCDfqvxHLdVETnAHFuttNzwhNQQzZN2fVVOq9ntY9Ar+J0xLsXwaE2nrkYRRfleKohM7zUlyhbhJc+sYFzwKOVe9c7Hvl5Kq1LT71bgR+0MKvs/yTQ8U1CobCYXLRUwW5Uz+EtvAe48h2a6R7GKsM2qy1KWgiwavjn6GpuBlC55+17hC8hlIzniO8nmNnBSiyABtFqtqsHjYaqQf9sWvrd0ex19NI="
  file: mscstts*.t*gz
  'on':
    tags: yes
    repo: muschellij2/mscstts

