language: R
sudo: false
cache: packages
after_success: if [ "$TRAVIS_OS_NAME" == "linux" ]; then Rscript -e 'covr::codecov(type
  = "all")'; fi
warnings_are_errors: true
before_deploy: if [ "$TRAVIS_OS_NAME" == "osx" ]; then rm -f *.tar.gz; fi
r_check_args: "--as-cran --install-args=--build"

deploy:
  provider: releases
  skip_cleanup: yes
  file_glob: yes
  api_key:
    secure: S4u97tzuZsanJPhZRLlWLmoQ3o/cFiZqvcKg8IZPDyXjsPnqzigAzpTeFwV7nv411CdHohYhmnqkVc2ujrDyGxbmWM0ec8OSJATg6a64xEKMOUuQonVzy194Nzbt2PWB8jfnVUDeo4G+5ld+jg+atSy/eXBRM3DcSJVFtPrKJgrvW8+m+ybGHMuU/RJHF22oKw5gFBZ0pRgGU027NBLZw+E6IVxt1pTejp7EGyHG/fCQPN5DZRG0q2u7XtqXwdFGpdtZnEKzWnTjqaHQTL2aduSp+eLlFbt6SRzRlbwjCTB7243GlJrxC4C745iHdDq+W5Z92k7+E7VyjvClnolvQwLEOpZMmob0I2IH2F4+FP9JT/jIT8BnOAfpc8hIBXTh2zOpYBgZIHxH+9ctddJ7vfn49nStL9vc87VbdytG340HnhnH/TDZcqIyWwF2ozSac5q4EBhXfR2nx8HdqnZO5sS9Xqfti6MEKTzYeZLZQu+uq3QYhqFZ7xZQ/07aiZ7a8eMirimjVTCN0EzuIxzIkst7l08p07RM2LvoqbQqYLdgBpP/hYQ8V3an3PdM6XYsJwJ9q1XI90AvkwHOUwPJMYM1gQjVnonNcqj4JcAx8i+kel62lK4HWnUJquYDTMrT7ywa85Rl1htMLCYoCtGY+N/qb9WR+aVYD2Srd7b31fk=
  file: mscstts*.t*gz
  'on':
    tags: yes
    repo: muschellij2/mscstts

